Default Exercise Details Page Unlogged
Healthy-Lifestyle-Assistant/frontend pull request #70
Opened 2023-11-03 19:19 UTC by TildaEndeavour

2023-11-06 14:31 UTC, Anastasiia2023 approved these changes

2023-11-06 19:26 UTC, OlegKDev requested changes

2023-11-06 19:26 UTC, OlegKDev commented on src/pages/workouts/DefaultExerciseDetailsPage.vue
> +            </div>
Let's place http refs in a row with wrap property instead of columns. Maybe, it will look better.

2023-11-06 19:26 UTC, OlegKDev commented on src/pages/workouts/DefaultExerciseDetailsPage.vue
> +        </div>
Please take a look at other files as examples, we write errors and warnings in JS by assigning message to a `message` variable.

2023-11-06 19:26 UTC, OlegKDev commented on src/pages/workouts/DefaultExerciseDetailsPage.vue
> +
If there are certain status codes, we can handle it with `if` and assign certain message to a `message` variable. 

```js

if (res.status === ...) {
      this.message = "...";
} else {
      this.message = "...";
}
```

2023-11-09 13:42 UTC, OlegKDev approved these changes

2023-11-09 13:42 UTC, merged