Manage User Profile Page #63
Healthy-Lifestyle-Assistant/frontend pull request #78
Opened 2023-11-16 17:12 UTC by Anastasiia2023

2023-11-24 11:35 UTC, TildaEndeavour approved these changes

2023-11-27 08:40 UTC, OlegKDev requested changes

2023-11-27 08:40 UTC, OlegKDev commented on src/users/pages/SettingsPage.vue
> +    <div class="d-flex flex-column align-items-center">
Please take a look at Media Update Page. Follow its css and code style.

2023-11-27 08:40 UTC, OlegKDev commented on src/router/index.js
> +        path: "/users",
Leave `settings`, or `user-settings` if you like.

2023-12-27 18:17 UTC, OlegKucherenkoDev approved these changes

2023-12-27 18:17 UTC, merged